### ISSUE TITLE
Doesn't work on Mac Pro

### ISSUE THREAD

**Issue by ronenmagid** [duskload/react-electron-webpack#1]
```
$ yarn start  
yarn run v1.16.0
$ npm-run-all --parallel bundle serve
$ webpack --mode development
$ electron .
App threw an error during load
/Users/ronenmagid/Downloads/react-electron-webpack-master/node_modules/picomatch/lib/picomatch.js:54
    let ignoreOpts = { ...options, ignore: null, onMatch: null, onResult: null };
                       ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ronenmagid/Downloads/react-electron-webpack-master/node_modules/picomatch/index.js:3:18)

webpack is watching the files…

Hash: 706a07c0e0f38c984bec
Version: webpack 4.39.1
Time: 1044ms
Built at: 08/05/2019 10:51:09 AM
     Asset       Size  Chunks             Chunk Names
bundle.css  128 bytes    main  [emitted]  main
 bundle.js   1.01 MiB    main  [emitted]  main
Entrypoint main = bundle.js bundle.css
[./client/src/Root.js] 464 bytes {main} [built]
[./client/src/reducers/index.js] 107 bytes {main} [built]
[./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 573 bytes {main} [built]
    + 43 hidden modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--5-1!client/src/components/styles.css:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
       2 modules
^[AVDCreateGPUAccelerator: Error loading GPU renderer
```

**Comment by duskload** [comment]
@ronenmagid, thanks for your report, sorry it takes so long.

Its fixed now.
